name: WakaTime Readme

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 20 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: CJWbiu/waka-readme@30days
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}